- name: set vm-name directories
  set_fact:
    vm_dir: "{{vms_dir}}/{{vm.name}}"

- name: stop/destroy vm
  virt:
    state: destroyed
    name: "{{vm.name}}"
  ignore_errors: true

- name: Undefine vm
  virt:
    command: undefine
    name: "{{vm.name}}"
  ignore_errors: true

- name: destroy vm images
  file:
    path: "{{vm_dir}}"
    state: absent
