- name: export locals

- name: install packages
  apt:
    name: "{{packaages}}"
    state: present
    update_cache: yes
  vars:
    packages:
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
      - virt-manager
      - cloud-image-utils

- name: add root as libvirt
  command: adduser root {{item}}
  with:
    - libvirt
    - libvirt-qemu

- name: start libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
