apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: ubuntu-vm-3
  labels:
    kubevirt.io/memory: "512"
    kubevirt.io/cpu-cores: "1"
    kubespray.io/image: ubuntu-1604
spec:
  replicas: 2
  selector:
    matchLabels:
      guest: {{-3
  template:
    metadata:
      labels:
        guest: ubuntu-vm-3
        kubevirt.io/memory: "512"
        kubevirt.io/cpu-cores: "1"
        kubespray.io/image: ubuntu-1604
    spec:
      domain:
        devices:
          disks:
            - name: cloudinitdisk
              volumeName: cloudinitvolume
              disk:
                bus: virtio
      volumes:
        - name: cloudinitvolume
          cloudInitNoCloud:
            userDataBase64: I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIG5hbWU6IGFudDMxCiAgICBzc2hfcHdhdXRoOiB0cnVlCiAgICBwYXNzd29yZDogdG90bwogICAgc3NoX2F1dGhvcml6ZWRfa2V5czoKICAgIC0gc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFDNzRNYXoyOHYrUmZOMW5teEJDaVF3cTM0NDdvL2tVZzZzWW5WY0dVbTJCU0Rocnp2SExNM0w5ZGRnNHFmc0FZM3JYZFl6NzFiMGhKNlZBbnRtckd4ZDN0blI5U2NWVjNQaGh1NUJkMUN2dWdxMFBtOC9ETlZQZWdFQzN6WGtJQ3BwRkxrMkNNRC9NU1AxWGs0RS8vYkhGZjRQaHRvWGNSMDc1Z2RjZngvUDVrajZlaml0UEtISjBUTXZXcHhlQ0VseE9lR0tQMVFFY1htSnZHTHJ5Nm9SRmRmTnR0UDRGZC9hemVXZDZrRkdBYWgzSURCUmR4S3VqT05TNXFOMTB6aEFSYVVZL2lLTTY0a0V4NjJkYWU5ZHgxSnJFaEMvYkdVN0NrWm5nTkxtMUtuNE9kK2Y2YWYzcFY5YkVJeXhzazhWUEw3bVhPOW1nT0todEUycE5OQXpKWDhCNnlFUVdlcHRNNzRxanR6RkZ6SzBaNUJrQW84QzhPV1VDV3JsV0luOVd3bHJRaGdSeWxCTHNoM2ExdllxTWt4aWg2d01iWVNCU0VubUpRRWFUTHJhdnJSK2huVGxjd244Ni9hK1VoWVJsbTFFK2dBZnl0bzZCaGlzSzVBczlxd0JJOVp6dUIrRjQ0RXVwSDBYeWJKQXMzNW9zVE4xREdPb0kyUFZsQUFpeSthbFh1WmNjaGtOV3J5TWVKWWFzZmlDYVE1MVhCMWc1VEN6R2ovQmtMUmR2dHJOdjhBYmZuTW1FUUZETy9QTzJkdE5iUmpSVFU2V3NzQVpuQjVqT2cwVXdLM3Z2VUdLWnVORmFFck53UXcwa2hZSkh6cWQ0WHRrVkFrS0YwMDJGblZraDA5dnZaZkxzUHY3SVR5QTUrUWF1UTdpZFVHNHRFNCt6c01yNVE9PSBub2RlQGt1YmVzcHJheS5jb20KCiAgLSBuYW1lOiByb290CiAgICBzc2hfcHdhdXRoOiAidHJ1ZSIKICAgIHBhc3N3b3JkOiB1YnVudHUKICAgIHNzaF9hdXRob3JpemVkX2tleXM6CiAgICAgIC0gc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFDNzRNYXoyOHYrUmZOMW5teEJDaVF3cTM0NDdvL2tVZzZzWW5WY0dVbTJCU0Rocnp2SExNM0w5ZGRnNHFmc0FZM3JYZFl6NzFiMGhKNlZBbnRtckd4ZDN0blI5U2NWVjNQaGh1NUJkMUN2dWdxMFBtOC9ETlZQZWdFQzN6WGtJQ3BwRkxrMkNNRC9NU1AxWGs0RS8vYkhGZjRQaHRvWGNSMDc1Z2RjZngvUDVrajZlaml0UEtISjBUTXZXcHhlQ0VseE9lR0tQMVFFY1htSnZHTHJ5Nm9SRmRmTnR0UDRGZC9hemVXZDZrRkdBYWgzSURCUmR4S3VqT05TNXFOMTB6aEFSYVVZL2lLTTY0a0V4NjJkYWU5ZHgxSnJFaEMvYkdVN0NrWm5nTkxtMUtuNE9kK2Y2YWYzcFY5YkVJeXhzazhWUEw3bVhPOW1nT0todEUycE5OQXpKWDhCNnlFUVdlcHRNNzRxanR6RkZ6SzBaNUJrQW84QzhPV1VDV3JsV0luOVd3bHJRaGdSeWxCTHNoM2ExdllxTWt4aWg2d01iWVNCU0VubUpRRWFUTHJhdnJSK2huVGxjd244Ni9hK1VoWVJsbTFFK2dBZnl0bzZCaGlzSzVBczlxd0JJOVp6dUIrRjQ0RXVwSDBYeWJKQXMzNW9zVE4xREdPb0kyUFZsQUFpeSthbFh1WmNjaGtOV3J5TWVKWWFzZmlDYVE1MVhCMWc1VEN6R2ovQmtMUmR2dHJOdjhBYmZuTW1FUUZETy9QTzJkdE5iUmpSVFU2V3NzQVpuQjVqT2cwVXdLM3Z2VUdLWnVORmFFck53UXcwa2hZSkh6cWQ0WHRrVkFrS0YwMDJGblZraDA5dnZaZkxzUHY3SVR5QTUrUWF1UTdpZFVHNHRFNCt6c01yNVE9PSBub2RlQGt1YmVzcHJheS5jb20KCg==
    - name: registryvolume
      registryDisk:
        image: {{registry}}/vm-{{key}}:latest
